# Generated by Django 3.2.3 on 2021-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210526_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.IntegerField(default=True),
        ),
    ]
