# Generated by Django 3.2.3 on 2021-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210526_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
